[package]
name = "learn_assert_cmd"
version = "0.1.0"
edition = "2021"

[dependencies]
predicates = "3.1.3"
once_cell = "1.20.3"
log = "0.4.25"
env_logger = "0.11.6"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
pretty_assertions = "1.4.1"

[env]
RUST_LOG = "trace"
FOO = "bar"